
package tp.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateurFinancierImplService", targetNamespace = "http://service.ws.tp/", wsdlLocation = "http://localhost:8282/calculateurFinancier?wsdl")
public class CalculateurFinancierImplService
    extends Service
{

    private final static URL CALCULATEURFINANCIERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATEURFINANCIERIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATEURFINANCIERIMPLSERVICE_QNAME = new QName("http://service.ws.tp/", "CalculateurFinancierImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/calculateurFinancier?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATEURFINANCIERIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATEURFINANCIERIMPLSERVICE_EXCEPTION = e;
    }

    public CalculateurFinancierImplService() {
        super(__getWsdlLocation(), CALCULATEURFINANCIERIMPLSERVICE_QNAME);
    }

    public CalculateurFinancierImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATEURFINANCIERIMPLSERVICE_QNAME, features);
    }

    public CalculateurFinancierImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATEURFINANCIERIMPLSERVICE_QNAME);
    }

    public CalculateurFinancierImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATEURFINANCIERIMPLSERVICE_QNAME, features);
    }

    public CalculateurFinancierImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateurFinancierImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateurFinancier
     */
    @WebEndpoint(name = "CalculateurFinancierImplPort")
    public CalculateurFinancier getCalculateurFinancierImplPort() {
        return super.getPort(new QName("http://service.ws.tp/", "CalculateurFinancierImplPort"), CalculateurFinancier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateurFinancier
     */
    @WebEndpoint(name = "CalculateurFinancierImplPort")
    public CalculateurFinancier getCalculateurFinancierImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.tp/", "CalculateurFinancierImplPort"), CalculateurFinancier.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATEURFINANCIERIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATEURFINANCIERIMPLSERVICE_EXCEPTION;
        }
        return CALCULATEURFINANCIERIMPLSERVICE_WSDL_LOCATION;
    }

}
